---

inherit_mode:
  merge:
    - Include

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.6

  Exclude:
    - demo/rails_demo/node_modules/**/*
    - demo/rails_demo/bin/**/*

Layout/LineLength:
  Max: 120

